# @format

runtime: nodejs16
service: default

env_variables: MONGO_URL: mongodb+srv://chatApp:chatApp@cluster0.mgoskpu.mongodb.net/?retryWrites=true&w=majority

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
